<?php

namespace ZIMZIM\Bundles\CategoryProductBundle\Entity;

use Doctrine\ORM\Query;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository implements iApyDataGridRepository
{
    public function getList($source)
    {
        $source->addHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        return $source;
    }

    public function getCountCategoryHomepage($id = null){
        $query = $this->createQueryBuilder('c');
        $query->where('c.homepage = :true')
            ->setParameter('true', true);

        if(isset($id)){
            $query->andWhere('c.id <> :id')
                ->setParameter('id', $id);
        }

        return $query->getQuery()->getResult();
    }
}
