<?php

namespace ZIMZIM\Bundles\CategoryProductBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getList($source, $locale)
    {
        $tableAlias = $source->getTableAlias();
        $source->manipulateQuery(
            function ($query) use ($tableAlias, $locale) {
            }
        );
        return $source;
    }
}
