<?php

namespace ZIMZIM\Bundles\CategoryProductBundle\Entity;

use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getList($source)
    {
        $source->addHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        return $source;
    }
    public function getCountProductHomepage($id = null){
        $query = $this->createQueryBuilder('p');
        $query->where('p.homepage = :true')
            ->setParameter('true', true);

        if(isset($id)){
            $query->andWhere('p.id <> :id')
                ->setParameter('id', $id);
        }

        return $query->getQuery()->getResult();
    }

}
